### ISSUE TITLE
Rechtschreibfehler 'Medlungen' zu 'Meldungen' korrigieren

### ISSUE THREAD

**Issue by inpercima** [bundesAPI/nina-api#2]
Hallo,

im Dokument https://github.com/bundesAPI/nina-api/blob/e7596c9ff375d15681c2ca201db0bc36dc7e7b67/openapi.yaml#L53 und an zwei weiteren darunter folgenden Stellen, hat sich ein kleiner Dreher eingeschlichen. Darauf wollte ich nur aufmerksam machen. ;)

**Comment by LilithWittmann** [comment]
Vielen Dank fürs Melden! Ist behoben! 🥳
