### ISSUE TITLE
RSS-Feed zur Dokumentation hinzufügen

### ISSUE THREAD

**Issue by jucktnich** [bundesAPI/nina-api#26]
Es gibt die Möglichkeit, Warnungen für einen Landkreis als RSS-Feed zu erhalten. Sollte dies auch zur Dokumentation hinzugefügt werden? (https://warnung.bund.de/api31/mowas/rss/{ARS}.rss)

**Comment by t-huyeng** [comment]
Meiner Meinung nach spricht nichts dagegen. Also gerne eine PR dafür machen 👍
